"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

Seq = [1,1]
QMax = 4000000
FiboFinal = 0

for i in range(33):
    Seq.append(Seq[-1] + Seq[-2])
print(Seq)

for i in Seq:
    if i < QMax:
        if i%2 == 0:
            FiboFinal += i
print("The sum of all even Fibonacci terms less than {} is {}".format(QMax,FiboFinal))